### ISSUE TITLE
Start crash

### ISSUE THREAD

**Issue by hannesa2** [lillithkt/Lilypad#1]
Nice, a Kotlin multiplatform repository !

Just for the records, it crashes during start
<img width="887" alt="image" src="https://github.com/user-attachments/assets/94c8b7b6-84f0-4f16-a24c-c688469bd314">

**Comment by hannesa2** [comment]
This is easy to solve, just by comment this `Spotube.init()`

**Comment by lillithrosepup** [comment]
fixed in 09c4903b6258773f960b8bf483bec8fa42f1ac49
