### ISSUE TITLE
Crash on updateAddress()

### ISSUE THREAD

**Issue by hannesa2** [lillithkt/Lilypad#2]
I see, I've to push "Update OSC" to start listening with OSC
![image](https://github.com/user-attachments/assets/fdb9bd5d-5daf-47ff-9c85-f8556af400d4)

But this crash 
<img width="696" alt="image" src="https://github.com/user-attachments/assets/929a97e9-4c1f-4016-8ebd-8872687b3970">

**Comment by hannesa2** [comment]
Is there a commit, where it works out of the box ?

**Comment by lillithrosepup** [comment]
fixed in 09c4903b6258773f960b8bf483bec8fa42f1ac49
